In [30]:
import pandas as pd

url1 = 'https://www.cbssports.com/mlb/standings/'
data = pd.read_html(url1)
standings = data[0]
columns = standings.iloc[0].tolist()
columns[0]='Team'
standings.columns = columns
x = standings[standings['Day'] != 'Day']
x.sort_values('L  Losses', ascending=False)

,Team,W Wins,L Losses,PCT Win Percentage,GB Games behind,Day,Night,Grass,Turf,One-Run,Extra,Vs RHP,Vs LHP,INTR,L10 Previous 10-games record
5,Baltimore,23,56,.291,30.0,9-22,14-34,22-50,1-6,5-13,4-5,13-37,10-19,6-9,4-6
11,Kansas City,25,55,.313,19.5,12-23,13-32,25-52,0-3,10-15,3-6,12-41,13-14,3-6,3-7
10,Chi. White Sox,28,51,.354,16.0,10-29,18-22,27-49,1-2,7-16,1-2,22-39,6-12,3-9,4-6
17,Texas,36,46,.439,18.0,10-15,26-31,33-43,3-3,9-9,6-2,25-31,11-15,4-4,8-2
9,Detroit,36,45,.444,9.0,20-18,16-27,36-45,0-0,13-11,4-3,25-37,11-8,1-7,2-8
4,Toronto,37,43,.463,16.5,18-17,19-26,16-18,21-25,10-10,8-1,28-22,9-21,7-3,5-5
8,Minnesota,34,42,.447,8.5,15-16,19-26,33-38,1-4,3-13,2-5,25-30,9-12,6-6,4-6
3,Tampa Bay,39,40,.494,14.0,17-19,22-21,19-24,20-16,14-19,3-3,24-28,15-12,2-7,7-3
16,L.A. Angels,41,40,.506,12.5,11-12,30-28,39-39,2-1,14-9,1-7,35-27,6-13,3-4,3-7
15,Oakland,43,38,.531,10.5,19-13,24-25,39-38,4-0,14-7,5-3,30-22,13-16,5-2,8-2
7,Cleveland,44,35,.557,—,20-12,24-23,43-34,1-1,10-11,1-5,29-27,15-8,7-4,8-2
14,Seattle,50,31,.617,3.5,14-14,36-17,45-29,5-2,25-11,7-0,35-19,15-12,1-1,4-6
13,Houston,54,28,.659,—,19-6,35-22,54-28,0-0,9-14,2-4,36-15,18-13,5-3,7-3
1,Boston,54,27,.667,—,20-5,34-22,45-23,9-4,13-8,3-3,42-18,12-9,4-1,6-4
2,N.Y. Yankees,52,26,.667,0.5,18-7,34-19,48-21,4-5,13-6,4-3,34-21,18-5,7-5,6-4